### ISSUE TITLE
add XSPF playlist files output

### ISSUE THREAD

**Issue by kidpixo** [gmusicproxy/gmusicproxy#104]
**First of all**: great project!

I'm "playing" with mpd/ncmpcpp/gmusicproxy to stream directly from gmusic. 

Working nicely*  using the playlist created with gmusicproxy.

**My problem is the lack of metadata in mpd**. mpd does not extract any information from the extended m3u playlist gmusicproxy produces, just everything is song title . From mpd plugin [ExtM3uPlaylistPlugin source](https://github.com/MusicPlayerDaemon/MPD/blob/0095e2d7d8a896f68ecb8fe51c294bca5a392008/src/playlist/plugins/ExtM3uPlaylistPlugin.cxx#L106):

```
/* unfortunately, there is no real specification for the
	   EXTM3U format, so we must assume that the string after the
	   comma is opaque, and is just the song name*/
```

One viable option to me is to implement another output format for gmusicproxy, specifically the [Xml Shareable Playlist Format (XSPF)](https://en.wikipedia.org/wiki/XML_Shareable_Playlist_Format). I can easily pipe all the info returned by `gmusicapi`/`get_all_songs` to an XML structure. 

**My question is: where do you think make more sense?** I see that all different api call to gmusicproxy have the playlist construction embedded, maybe would make more sense to have an extra function to assemble the output, given the songs collection and the format ?

I'm asking because I have little experience with API endpoint _et smilia_.

I'll start to implement this for the `/_get_collection` endpoint on a fork.

---

\* My setup is mac 10.12.6,  mpd/ncmpcpp installed via homebrew.

**Comment by diraimondo** [comment]
Hi!
It could make sense but would get more information on XSPF format. I understand that it is a format for playlist that can handle metadata. I assume mpd can get such data crom a XSPF playlist. It could be possible to add such format in gmusicproxy. On any api request that reports an m3u playlist you could add a `format` parameter (with default m3u) to revert on XSPF. Few of them support a simple txt list already. I would be a quiet invasive change. It was my first Python project and I'm not very proud of its internal structure... but it works...
I can't work on the project in this period but your contribution are welcome.
