### ISSUE TITLE
Looking for a new Maintainer for GMusicProxy

### ISSUE THREAD

**Issue by diraimondo** [gmusicproxy/gmusicproxy#105]
During last year I had few time to improve the project and no interest in developing new features: sorry. I'm no more an active user of the Google service. I kept the subscription on only for the project: many thanks for the donations.

Now I would like to find a new maintainer for the project: any active user willing to succeed me. Modest skills in Python programming are necessary: that was my fist project in Python and anyone can be better than me in this. The project would require a better rewrite but it just works now...

The interested person could reply to this issue. Anyone with already public projects would be preferred.

**Comment by diraimondo** [comment]
It looks no one is interesting in maintaining GMusicProxy: maybe it will become an abandonware...

**Comment by whyorean** [comment]
@diraimondo 

Thanks a lot for your work.
I would like to extent your work, but on another (Android) platform, I am developer of [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore) (An open source PlayStore alternative) and now I want a PlayMusic alternative, after a lot of searches I landed here.

I may not be able to maintain Python oriented GMusicProxy, but will surely maintain its Android client.

If you have time and patience kindly let me know, I need just basic data to startup with it.

Email : whyorean@gmail.com
Telegram : @whyorean

**Comment by diraimondo** [comment]
@whyorean Hi! You could even think to use gmusicproxy as internal engine to make your Android client work. The powerful tool that made possible gmusicproxy is the great gmusicapi. You could use it (I don't know how python library can be used in Android...). 
I can't remember interfacing library like gmusicapi in Java. I'm quiet sure that BumbleUPnP can connect to Google Music but I think it use some kind of internal library (in Java). You can start from there.

Good luck!

**Comment by whyorean** [comment]
Thanks mate, but I think I need to write my own java api based on gmusicproxy/gmusicapi.

**Comment by jdwoody** [comment]
@diraimondo I'm interested in maintaining the project. I'm writing a GMusic plugin for Volumio and using GMP on the back end.

**Comment by diraimondo** [comment]
Hi, I've just invited you as collaborator. Feel free to get the management of the code with new releases. I let expire the domain gmusicproxy.net so you should remove any reference to it (also the function in the code that check if there are new releases).

**Comment by aleqcz** [comment]
Super, good luck and thanks!

**Comment by jdwoody** [comment]
@diraimondo Are you opposed to me creating an organization account for the code - github.com/gmusicproxy? That will allow us to use github pages to host the site docs as well

**Comment by diraimondo** [comment]
@jdwoody it is fine for me to create an organization account to manage gmusicproxy related code. I have no experience in this so feel free to manage it.

**Comment by jdwoody** [comment]
@diraimondo I'm not sure if there's a way to transfer references, I'll research it. I set up the organization and added you. I also set up a repository for the github pages. Could you push the old website html to the gmusicproxy.github.io repo when you have a moment?

**Comment by diraimondo** [comment]
Ok, I did the transfer of the source repository. It looks the original references are still working.
I still have the php pages from the old domain gmusicproxy.net but they just manage to display in html the Readme.md file of the repository using flatdoc. I guess you can link such file from the source repository of create a new kind of site.

**Comment by jdwoody** [comment]
Got the new site up and just used the README as a start. If you want to add any additional information to the site, feel free.
