### ISSUE TITLE
Hi, Impossible to start

### ISSUE THREAD

**Issue by monat78** [gmusicproxy/gmusicproxy#107]
Hi, i put -e email -p password and --device-id, but is impossible... 

Can you help me?? Regards

Sorry, those credentials weren't accepted

**Comment by jdwoody** [comment]
Couple of suggestions. Generally easier to use a config file and start the server using:
GMusicProxy -c /path/to/your/file.cfg
The config file should be in this format:
```
email = you@yourdomain.com
password = your_secure_password
device-id = your_device_id
```
If you have 2 factor authentication (2FA) enabled, you probably need to create an App Password in your Google settings.

**Comment by monat78** [comment]
yes.. i need create a password app without 2 factor authentication :D is ok,,, thanks for suggestions :+1:

**Comment by jdwoody** [comment]
I've added a better error message for the next release to suggest creating an App Password.
