### ISSUE TITLE
Create an official, Automated Build image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [gmusicproxy/gmusicproxy#109]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, documentation could easily include a canonical `docker run` statement to quickly run the software with just a single command.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays AB when listing images.

Just a free Docker Hub account and a quick setup would do. You already have the Dockerfile :). Ping me if you need help.

**Comment by pataquets** [comment]
@mario-tux ping

**Comment by mario-tux** [comment]
I'm not maintaining gmusicproxy anymore. Sorry. There is another maintainer.

**Comment by pataquets** [comment]
Ops! Sorry to bother you, @mario-tux. I've just assumed it, since you're the main commiter. My apologies.
I've looked closely at the readme, but no clue. Latest PRs were merged also by you. I'm not even sure if this repo is currently maintained or it is in another fork. There is jdwoody (not mentioning in case it's not him/her) who answered some recent issues, but not sure. Can you point me to which repo / who the maintainer is now? Thank you.

**Comment by jdwoody** [comment]
@pataquets I looked at this a bit. Would like to update the image to use python 3. PRs are welcome : )

**Comment by pataquets** [comment]
Thanks for you prompt reply @jdwoody. I didn't realize that it's on Py2, and looking at the commits you're working on moving into Py3, if I'm not wrong.
I was just requesting to have a base working image to start tinkering with.
However, I see no hard dependency on creating the AB with the Py2 base image, unless you say so ;)
If there is interest in creating an AB, I might give it a stab, since it doesn't looks like a lot of work (I've taken a quick look, though) and even has room for improvement. You can even set up the AB and see if it works, and with subsequent PRs, we could even check if the AB works.
Let me know if you're interested, or go ahead and set it up to have a starting point. I agree on the convenience of using Py3 and I can lend a hand if this improves the built image.

**Comment by jdwoody** [comment]
@pataquets ```docker pull gmusicproxy/gmusicproxy:2.1.1```
