### ISSUE TITLE
get_playlist hangs

### ISSUE THREAD

**Issue by sglickman** [gmusicproxy/gmusicproxy#112]
gmusicproxy hangs with get_playlist. I initially thought this was because the playlist contained uploaded tracks (I'm not sure if this means that the tracks don't have IDs? see issue #111) but I just created a new playlist which contains a single AA track.

get_all_playlists works great but then when I try to use one of the URLs returned, nothing happens. 

The terminal running gmusicproxy:
<code>
<pre>
[18/Nov/2019 23:39:30] "GET /get_playlist?id=3a62f60a-30b3-4236-9266-00417fcfbf29 HTTP/1.1" 200 -
Getting tracks from playlist with id '3a62f60a-30b3-4236-9266-00417fcfbf29'
</pre>
</code>

and then doesn't progress any further (no output, no error message, the command doesn't complete).

**Comment by MarcelloTheArcane** [comment]
I've noticed everything hangs, including `get_song`. Google Music must have changed something...

**Comment by sglickman** [comment]
`get_song` seems to be working ok for me, other than some odd ID3 issues where the metadata tags don't get read correctly by a Sonos which I'm still trying to figure out.

**Comment by jdwoody** [comment]
@sglickman @MarcelloTheArcane Which version of Python and GMusic Proxy? I'm running on a branch right now and can cut a release if needed. I'm not able to reproduce though.

**Comment by sglickman** [comment]
I'm using Python 2.7, and checked out the current master branch of GMusicProxy.

My ultimate goal is use this along with <a href="https://github.com/SoCo/SoCo">SoCo</a> to programmatically play a given GPM album on my Sonos at home. I'm currently doing this by mapping each album to the GPM ID, querying for the tracklist m3u and adding the mp3 files to the Sonos controller (made a couple small tweaks to allow ".mp3" as a GMusicProxy get_song suffix so that the Sonos wouldn't freak out, as well as a very small "?" escape/unescape thing, in case anyone else is also trying to do the same).

This works fine enough for the regular albums, but doesn't work at all for the uploaded content. Can't query for it, can't get an album ID, can't even load a playlist containing uploaded tracks. 

I <b>can</b>, however, get_song with the uploaded ID; instead of a T prefix it'll be some very long hex code like "21c1467d-bfc0-3568-a734-00f0e266b07b" (you can view them in a DOM inspector as data-id attributes attached to the &lt;tr&gt; elements on the GPM web client) - this loads and streams properly.

The other issue involves the ID3 tags - I can see them being added in the code, but they don't seem to come through in quite the correct way for a streaming mp3. If I open, say, http://raspberrypi:9999/get_song?id=Tr4cp2rk6yvlg5evbd5lclebaay.mp3 in VLC, the music starts playing but there's no title, artist, album art etc. If I download the mp3 first everything appears correctly. This presents a minor issue on the Sonos as all of the track titles are some gibberish like "get_song?id=Tr4cp2rk6yvlg5evbd5lclebaay.mp3" but I'm hoping to find some time to sit down and resolve that soon.

**Comment by jdwoody** [comment]
I'm aware of the ID3 issue and I think I also cleaned that up a bit on the branch. If possible, do a 
`git pull && git checkout jsonendpoint`
`git log` should show the latest commit as `b6baaeb74b0e8c3bc13f6d014edbc6aca5f2b7c5`. Try to run that branch and let me know what happens.

Also, do you have All Access subscription or are you on a free account?

**Comment by sglickman** [comment]
oh great! i'll give it a shot later tonight. I'm on All Access.

**Comment by sglickman** [comment]
Hm just tried jsonendpoint and no luck with VLC recognizing the tags.

**Comment by jdwoody** [comment]
Any chance you could make the m3u available to download? Wondering if there's an encoding issue.

**Comment by jdwoody** [comment]
@MarcelloTheArcane @sglickman Can you let me know if this is still an issue. I cut a new release that uses an updated version of the gmusicapi and I'm seeing metadata within VLC.

**Comment by MarcelloTheArcane** [comment]
@jwoody it looks like something is working again now, thanks!

**Comment by MarcelloTheArcane** [comment]
@jdwoody it looks like something is working again now, thanks!

**Comment by MarcelloTheArcane** [comment]
@jdwoody it looks like something is working again now, thanks!

**Comment by sglickman** [comment]
I'm still not seeing metadata in VLC trying to open a get_song URL

**Comment by sglickman** [comment]
but again I'm opening the stream directly (both in VLC to test & also in Sonos)

**Comment by jdwoody** [comment]
@sglickman I was able to get the meta data partially displayed in vlc using the icecast options. I'm testing with XSPF and will follow up with you if that's a better solution.

**Comment by jdwoody** [comment]
@sglickman Give the latest release (2.1.0) a try with the xml/xspf formatted results. Pulled up in VLC with all metadata correctly.

**Comment by sglickman** [comment]
Works in VLC - thanks!

**Comment by jdwoody** [comment]
@sglickman if you have info on your set up, drop me an email or a link here. Have another user that is interested in a similar setup - GMP, SoCo, etc.

**Comment by sglickman** [comment]
Sure, I have some relatively simple glue software that does a couple of apparently-necessary URL-handling features which Sonos seems to need. The two big ones seem to be escaping the "?" in the URL, and allowing a file suffix of ".mp3"

Sonos still doesn't seem to be fetching the metadata correctly but that's a pretty minor issue all things considered. Just waiting for the GPM transition to YTM to drop...

**Comment by sglickman** [comment]
https://github.com/sglickman/sonos_gpm

**Comment by sglickman** [comment]
GMusicProxy meanwhile has 2 lines of changes:

@@ -84,6 +84,7 @@ class GetHandler(BaseHTTPRequestHandler):
     REQ_PATH = 'REQUEST_PATH'
 
     def do_GET(self):
+        self.path = self.path.replace("%3F", "?")
         self._process_request('GET', self.server.get_handlers)
 
     def handle_song(self, params):
@@ -229,6 +230,7 @@ class GetHandler(BaseHTTPRequestHandler):
         return metadata.encode('utf-8')
 
     def _get_song(self, id, only_headers=False):
+        id = id[:-4] if id.endswith(".mp3") else id
         info = self._get_song_info(id)
         if info is None:
             logger.info('Streaming song with id \'%s\'', id)

**Comment by sglickman** [comment]
final comment - the actual collection/album/NFC link is stored in a google spreadsheet that looks like this:

https://docs.google.com/spreadsheets/d/1gLGB7VpOMSDH9SL6pIcsL4-VYdgZGlGjJ2ZgI8sPnk4/edit?usp=sharing

some of the columns are unused/speculative

**Comment by jdwoody** [comment]
Are the GMP changes something that the sonos needs? If so, you could open an issue and we could add a flag for it so you wouldn't have to patch.

RE: YTM - I still haven't seen a music API published, hoping they don't shut GMP down before offering that.

**Comment by sglickman** [comment]
Sonos seemingly won't accept an un-escaped URL

Using SoCo's add_uri_to_queue: 
```
>>> player.add_uri_to_queue("http://raspberrypi:9999/get_song?id=Tv2flcvrtsu532viwx6yz62pvm4.mp3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/soco/core.py", line 105, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/soco/core.py", line 1482, in add_uri_to_queue
    return self.add_to_queue(item, position, as_next)
  File "/home/pi/.local/lib/python2.7/site-packages/soco/core.py", line 105, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/soco/core.py", line 1505, in add_to_queue
    ('EnqueueAsNext', int(as_next))
  File "/home/pi/.local/lib/python2.7/site-packages/soco/services.py", line 217, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/soco/services.py", line 501, in send_command
    self.handle_upnp_error(response.text)
  File "/home/pi/.local/lib/python2.7/site-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 804 received:  from 192.168.86.250
```

Sonos allows the escaped version, but then doesn't unescape it to fetch the URL from GMP. I'm not sure if it needs to be behind a flag, as I don't think it makes any difference if you're not passing GMP escaped URI's (though perhaps the official unescape should use a real url-parsing library).

```
>>> player.add_uri_to_queue("http://raspberrypi:9999/get_song%3Fid=Tv2flcvrtsu532viwx6yz62pvm4.mp3")
```


Sonos similarly won't accept it unless the string ends in .mp3 and I also wouldn't think this change would need to live behind a flag.

**Comment by sglickman** [comment]
but you definitely don't need to add those changes just for my use case, I'm fine with just tweaking things locally. this is just a toy project 😛

**Comment by sglickman** [comment]
https://www.theverge.com/21254766/google-play-how-to-transfer-music-youtube-playlists-uploads-library 

> Google Play Music is going away at the end of the year

😭

**Comment by jdwoody** [comment]
I saw that, we could probably move this with a little work to use the you tube api:
https://github.com/sigma67/ytmusicapi
Thoughts?

**Comment by MarcelloTheArcane** [comment]
It looks like that gives you YouTube video IDs, so we'll lose the nice album arts and high quality mp3 files unless they will store them too.
