### ISSUE TITLE
get_by_search error

### ISSUE THREAD

**Issue by monat78** [gmusicproxy/gmusicproxy#113]
File "GMusicProxy", line 157, in do_GET
    result = self._search(type=params['type'][0].lower().strip() if 'type' in pa                                                                                        rams else 'artist', query_title=params['title'][0].decode('latin-1') if 'title'                                                                                         in params else '', query_artist=params['artist'][
AttributeError: 'str' object has no attribute 'decode'

**Comment by jdwoody** [comment]
@monat78 Can you provide some additional information? Python version, GMP version, maybe the search string you used?

**Comment by monat78** [comment]
i have use python3, with the last GMP version, and /lib/python3.7/dist-packages/gmusicapi-13.0.0.tar.gz

**Comment by jdwoody** [comment]
I didn't get any errors, but I'm still running on Python 2 build. Give me a little time and I'll test it on 3.7 to try and reproduce.

**Comment by jdwoody** [comment]
@monat78 I see the issue. I'll cut a release soon, doing some testing. This has to do w/partial Python 3 compatibility. I'm removing all Python 2 code now.

**Comment by jdwoody** [comment]
@monat78 Try this again with the latest version and let me know if you still have issues.

**Comment by monat78** [comment]
all is ok 
🗡️ 
good job
