### ISSUE TITLE
/get_new_station_by_search is broken

### ISSUE THREAD

**Issue by jeffmhubbard** [gmusicproxy/gmusicproxy#115]
Lines 164 and 165 are commented out, breaking /get_new_station_by_search

https://github.com/gmusicproxy/gmusicproxy/blob/a2622372b35ea6a09ee47656350976e0247ea659/GMusicProxy#L155-L166

**Comment by jdwoody** [comment]
@jeffmhubbard Will have this fixed in a day or so

**Comment by jdwoody** [comment]
@jeffmhubbard Open a ticket if you have any other problems.
