### ISSUE TITLE
Plans or thoughts on OAuth?

### ISSUE THREAD

**Issue by jeffmhubbard** [gmusicproxy/gmusicproxy#117]
GMP has been throwing this warning:
```
<decorator-gen-76>:2: GmusicapiWarning: login is deprecated and may break unexpectedly; prefer Mobileclient.oauth_login
```

Do you have any plans on switching yet? Support was added in [this fork](https://github.com/M0Rf30/gmusicproxy) some time ago and works well. And it looks like `api.login()` has actually been deprecated in `gmusicapi` since 11.1.0 (2018-11-30). I would submit a PR, but I wanted to get your input first.

The above fork has dropped keyring and config file altogether. It works well, but requires a browser. Nothing to support headless or remote servers that I know of. So those changes would obviously break some setups.

**Comment by jdwoody** [comment]
I've seen the warning, but haven't spent time testing oauth. Go ahead and submit a PR. I'm not sure if anyone uses the keyring feature, but have no issues removing it. Just a quick review of commits in the fork and see there other features we could merge as well.

**Comment by jeffmhubbard** [comment]
Okay, I'll to put something together soon. I'm moving this weekend, so I don't know when I will be able to get to it.

The other features (get_promoted and the "listen now" features) actually came from my fork. I was planning to submit those soon, but it needs to be made to work with the new `do_GET`.

**Comment by jgrocho** [comment]
I just put together an OAuth PR #118. You both might want to take a look at it. The way gmusicapi does oauth the user can open the URL on any device so headless setups should still work, although they do have to be interactive at least once.

It leaves in the email/password setup and keyring features, but uses oauth if none of them are used.

**Comment by jdwoody** [comment]
I agree, headless should be fine, I've done this for other applications without issue. I'm not sure how it will work with Docker.

**Comment by jdwoody** [comment]
Merged, thanks @jgrocho
