### ISSUE TITLE
Enhancement:  Support gmusicapi situations

### ISSUE THREAD

**Issue by ghost** [gmusicproxy/gmusicproxy#78]
It would be nice if the gmusicapi situation playlists were supported, not sure how feasible this is.

http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html?highlight=situations#gmusicapi.clients.Mobileclient.get_listen_now_situations

**Comment by diraimondo** [comment]
It is feasible but it requires time (very scarce for me at the moment). In TODO list.

**Comment by jdwoody** [comment]
Added in version 2.2.0
