### ISSUE TITLE
feature request: save album/track covers

### ISSUE THREAD

**Issue by prietus** [gmusicproxy/gmusicproxy#94]
it would be nice having the ability of saving the jpeg embedded image with eyeD3 to a desired folder. e.g mpd cannot deal with them. putting it in context: lets say you do  gnome + media player indicator + mpdris2. you cannot see album art.
regards

**Comment by diraimondo** [comment]
Would be suitable for your scenario to provide an new url-command like `get_album_cover?id=id_of_the_song` that reports the related jpeg? 
I don't like to much the idea to save the images in a folder: what name should they get?

**Comment by prietus** [comment]
yeah that would be great. I meant I think the correct place is doing it from gmusicproxy itself, since you already deal with eyeD3 tags there. for doing it externally you have to download tracks again just for extracting covers with ffmpeg or eyeD3. regarding how you implement it i's up to you since you know the sw better. hmm my english is weak when you say "that reports the related jpeg" you mean being able to get the jpeg file? 
eyeD3 --write-images=Imágenes "http://192.168.199.33:9999/get_song?id=Tbi5hkkbe4ir4rsjkhsl5v7lqti" won't work and ffmpeg -i "$1" -vcodec copy ~/"$track_name".jpg downloads the whole track that's why I asked about a saner method.
regards.

**Comment by diraimondo** [comment]
I mean a method that you can use with `wget` to download the jpeg file.

**Comment by prietus** [comment]
yeah, that would be great

**Comment by prietus** [comment]
it would make sense a setting a way of enabling it globally? as in --albumart /path/to/dir?

**Comment by diraimondo** [comment]
@prietus I don't understand your last question: what folder do you mean? I don't want gmusicproxy to deal with a local folder where it should put the images. It will provide a method to get a single album cover thought the HTTP protocol. You will have to download it using wget (for example) and than you will use it as you like: passing it to a suitable client or storing on a folder...

**Comment by prietus** [comment]
fair enough. any method you consider for being able to grab album art is appreciated.
regards

**Comment by prietus** [comment]
I see:
                albumArt = opener.open(info['albumArtRef'][0]['url']).read()
                tags.images.set(3, albumArt, "image/jpeg")
which is enough for me as I can:
                 img = Image.open(io.BytesIO(albumArt))
                 img = img.save(/path/to/folder)
Thanks.
